on:
    workflow_dispatch:
      inputs:
        branch:
          description: "branch"
          required: true
          type: string

        letters:
          description: "letters"
          required: true
          type: string

jobs:

  run-workflow:
    runs-on: ubuntu-latest

    steps:
        - name: echo something
          run: echo "Running on main (${{ inputs.branch }}) with letters ${{ inputs.letters }}"
